[package]
name = "example"
version = "0.2.2"
authors = ["David Tolnay <dtolnay@gmail.com>"]

[dependencies]
demo-hack = { path = "../demo-hack" }
demo-hack-impl = { path = "../demo-hack-impl" }
proc-macro-hack = { path = ".." }
