[package]
name = "example"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/dtolnay/proc-macro-hack"
edition = "2018"
publish = false

[dependencies]
demo-hack = { path = "../demo-hack" }
