[package]
name = "example"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[dependencies]
demo-hack = { path = "../demo-hack" }
demo-hack-impl = { path = "../demo-hack-impl" }
proc-macro-hack = { path = ".." }
