sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - cargo run --manifest-path example/Cargo.toml

matrix:
  include:
    - rust: nightly
      name: Minimal versions
      before_script:
        - cargo update -Z minimal-versions --manifest-path example/Cargo.toml
