[package]
name = "demo-hack"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[dependencies]
proc-macro-hack = { path = ".." }
proc-macro-hack-impl = { path = "../impl" }
